name: readme_and_act
description: Puts your latest activity on github in your README, implemented in Python.
author: WardDeb

inputs:
  GH_USERNAME:
    description: "Your GitHub username"
    default: ${{ github.repository_owner }}
    required: false
  MAX_LINES:
    description: "The maximum number of lines to place in your readme file"
    default: 5
    required: false
  TARGET_FILE:
    description: "The file location to write changes to"
    default: "README.md"
    required: false

runs:
  using: docker
  image: Dockerfile
